-- Snowflake demo — provider folder mapping.
--
-- The Snowflake-native replacement for the hardcoded FOLDER_TO_PROVIDER /
-- PROVIDER_GLOB dicts in scripts/lambda_function_glue.py. Rows here are
-- generated from config/providers/*.yaml by
-- python/matchbot_snowflake/config_bridge.py (MERGE INTO, idempotent) —
-- never hand-edited, so this table can't drift from the YAML the way the
-- two Lambda dicts can from each other.
--
-- PRIMARY KEY is (folder_name, file_glob), not folder_name alone: a
-- multi_file provider (e.g. RISOS) can have several ProviderConfigs
-- sharing one folder_name (risos_voter) but each with its own file_glob
-- (Voter_*.txt vs VoterHistory_*.txt) and its own column_mappings/
-- matches_dataset — run_pipeline.py resolves which row applies to an
-- incoming file by matching its filename against each candidate row's
-- file_glob (fnmatch), not by folder_name alone. A single-file-type
-- provider (RIDE) still gets exactly one row, so its behavior is
-- unchanged — this is additive, not a behavior change for RIDE.

USE DATABASE MATCHBOT;
USE SCHEMA RILDS;

CREATE TABLE IF NOT EXISTS PROVIDER_FOLDER_MAP (
    folder_name         VARCHAR(100) NOT NULL,               -- S3 key's provider-folder segment, e.g. 'ride_enrollment'
    provider_id         VARCHAR(100) NOT NULL,              -- ProviderConfig.provider_id
    provider_code       VARCHAR(20)  NOT NULL,               -- ProviderConfig.provider_code
    dataset_name        VARCHAR(100) NOT NULL,               -- ProviderConfig.dataset_name
    file_glob           VARCHAR(200) NOT NULL,               -- ProviderConfig.file_glob
    external_id_column  VARCHAR(50),                         -- ProviderConfig.external_id_column, e.g. 'sasid'
    -- ProviderConfig.delimiter, e.g. ',' for RIDE, '|' for RISOS. Read by
    -- run_pipeline.py to pick the matching Snowflake file format via
    -- land_sql.py's csv_format_for_delimiter() — added when onboarding
    -- RISOS, whose pipe-delimited file exposed that the land step was
    -- hardcoded to comma (CSV_PROVIDER_FORMAT) with no per-provider override.
    delimiter           VARCHAR(5)   NOT NULL DEFAULT ',',
    -- ProviderConfig.multi_file. FALSE (default) keeps a provider's land
    -- table name exactly {provider_code}_land (e.g. RIDE_LAND, unchanged).
    -- TRUE means this provider ships multiple structurally distinct files
    -- under one folder (e.g. RISOS: voter registration + voter history) —
    -- run_pipeline.py then names each file's land table
    -- {provider_code}_{file_type}_land, file_type derived from the
    -- filename (land_sql.py's file_type_from_filename), so two unrelated
    -- file shapes never collide on one table.
    multi_file          BOOLEAN      NOT NULL DEFAULT FALSE,
    -- ProviderConfig.matches_dataset. FALSE for a file type that only
    -- lands + transforms and never runs person-linkage matching (e.g.
    -- RISOS VoterHistory) — run_pipeline.py stops after that file type's
    -- own transform step and never touches RILDS_STAGE/WINNERS/matching.
    matches_dataset     BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Full raw-column -> canonical-attribute mapping, straight from this
    -- file type's ProviderConfig.column_mappings (e.g. {"FIRST_NAME":
    -- "first_name", "DATE_OF_BIRTH": "birth_date", ...}) — the Snowflake-
    -- table equivalent of legacy's per-model `identifiers = {...}` dict
    -- (risos/models/voter.py etc.), except generated from YAML instead of
    -- hand-coded per provider. NULL for a provider with no mappings
    -- (shouldn't happen in practice, but not enforced NOT NULL since an
    -- empty/absent dict is a legitimate edge case for a land-only file type).
    column_mappings     VARIANT,
    -- Human-readable, deduplicated list of attributes the RESOLVED matcher
    -- chain actually compares on for this file type (e.g. ["External ID",
    -- "First Name", "Last Name", "Birth Date"]) — computed the same way
    -- notify_sql.py's matched_on_attributes()/the AWS email's "Matched on"
    -- line already do (config/global.yaml's matcher chain filtered down to
    -- only the rules this provider's column_mappings actually support), not
    -- a hand-picked subset. Regenerated by config_bridge.py on every MERGE,
    -- so it can't silently drift if global.yaml's matcher chain changes —
    -- re-run the MERGE after any matcher-chain edit to refresh this column.
    matching_identifiers ARRAY,
    updated_at          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (folder_name, file_glob)
);

-- Already-deployed accounts: add the two new columns (metadata-only,
-- existing rows read NULL here until the next MERGE re-run backfills them
-- — same idempotent-regeneration story as every other column here).
ALTER TABLE PROVIDER_FOLDER_MAP ADD COLUMN IF NOT EXISTS column_mappings VARIANT;
ALTER TABLE PROVIDER_FOLDER_MAP ADD COLUMN IF NOT EXISTS matching_identifiers ARRAY;

-- Existing deployments created this table with folder_name as the sole
-- PRIMARY KEY and no matches_dataset column — a PRIMARY KEY can't be
-- altered in place in Snowflake, so an already-deployed table needs to be
-- dropped and recreated (safe: every row here is regenerated idempotently
-- from config/providers/*.yaml, nothing hand-authored is ever stored here).
-- CREATE TABLE IF NOT EXISTS above is a no-op against such a table, so
-- run this once by hand when upgrading a pre-existing deployment:
--   DROP TABLE PROVIDER_FOLDER_MAP;
--   -- then re-run this file, then re-run config_bridge.py's generated MERGE.

-- Tracks which staged files have already been processed, so the polling
-- Task never reprocesses a file it already ran.
CREATE TABLE IF NOT EXISTS INGEST_LOG (
    file_path        VARCHAR(1000) NOT NULL PRIMARY KEY,  -- relative path within the stage, e.g. data/input/ride_enrollment/foo.csv
    provider_id      VARCHAR(100) NOT NULL,
    first_seen_at    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    status           VARCHAR(20)  NOT NULL DEFAULT 'PENDING',  -- PENDING | SUCCESS | FAILED
    pipeline_run_id  NUMBER,
    error            VARCHAR(4000)
);
