"""add address1_std, zip5, ssn4 columns for name+address/name+ssn4 matchers

Adds address1_std/zip5/ssn4 to every table sharing
storage.schema._identity_columns() (rilds_stage, rilds_matched, rilds_error,
member_universe) — backing the new deterministic_name_ssn4 and
deterministic_name_addr_full/city_state/street_zip/fn_addr matcher tiers,
plus the fuzzy_name_addr_combined tier's ssn4/zip5 corroborating
comparisons.

Also adds address1_std/zip5 to rilds_reference (a separate column set from
_identity_columns() — see ad1d30248bfe's docstring for why). Unlike
first_name_std/last_name_std, which proddb precomputes into the source data
before it ever reaches this repo, address1_std/zip5 have no such external
producer today — this migration only adds the columns; existing rows read
NULL here until an out-of-band process backfills them (see
docs/snowflake-implementation-plan.md's matching-logic discussion — the
same assumption applies to the Snowflake-side RILDS_REFERENCE).

Hand-written rather than autogenerated, same reasoning as ad1d30248bfe: this
project's blocking indexes are created via raw CREATE INDEX
(storage.schema.extra_index_sql), which Alembic's autogenerate cannot see.

Revision ID: 1e54b964137b
Revises: ad1d30248bfe
Create Date: 2026-07-23 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e54b964137b'
down_revision: Union[str, Sequence[str], None] = 'ad1d30248bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Tables sharing storage.schema._identity_columns().
_IDENTITY_TABLES = ("rilds_stage", "rilds_matched", "rilds_error", "member_universe")

_NEW_IDENTITY_COLUMNS: list[tuple[str, sa.types.TypeEngine]] = [
    ("ssn4", sa.String(4)),
    ("address1_std", sa.String(200)),
    ("zip5", sa.String(5)),
]

_NEW_REFERENCE_COLUMNS: list[tuple[str, sa.types.TypeEngine]] = [
    ("address1_std", sa.String(200)),
    ("zip5", sa.String(5)),
]


def upgrade() -> None:
    for table in _IDENTITY_TABLES:
        for name, col_type in _NEW_IDENTITY_COLUMNS:
            op.add_column(table, sa.Column(name, col_type, nullable=True), schema="rilds")

    for name, col_type in _NEW_REFERENCE_COLUMNS:
        op.add_column("rilds_reference", sa.Column(name, col_type, nullable=True), schema="rilds")


def downgrade() -> None:
    for name, _col_type in reversed(_NEW_REFERENCE_COLUMNS):
        op.drop_column("rilds_reference", name, schema="rilds")

    for table in _IDENTITY_TABLES:
        for name, _col_type in reversed(_NEW_IDENTITY_COLUMNS):
            op.drop_column(table, name, schema="rilds")
