"""generalize sasid to rilds_id, add ssn and address columns

Renames the sasid column to the generic rilds_id (holds whatever value a
provider's member_external_id mapping supplies — SASID, a future CCRI id,
etc. — see ProviderConfig.external_id_column) and adds ssn/address1/
address2/city/state/zip, on every table that shares
storage.schema._identity_columns(): rilds_stage, rilds_matched, rilds_error,
member_universe. rilds_reference is untouched — it keeps its own per-agency
id columns (sasid, ccri_id, ...) since it is the merged, multi-agency answer
key, not a per-provider table.

Hand-written rather than autogenerated: this project's blocking indexes are
created via raw CREATE INDEX (storage.schema.extra_index_sql), which
Alembic's autogenerate cannot see, so a diff run at this revision proposes
dropping/recreating every table. This migration only performs the actual
intended change.

Revision ID: ad1d30248bfe
Revises: 17dfdd5618cc
Create Date: 2026-07-08 11:49:55.199412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1d30248bfe'
down_revision: Union[str, Sequence[str], None] = '17dfdd5618cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Tables sharing storage.schema._identity_columns() — every one of them gets
# the same rename + new columns so stage/matched/error/member_universe never
# drift from each other.
_TABLES = ("rilds_stage", "rilds_matched", "rilds_error", "member_universe")

_NEW_COLUMNS: list[tuple[str, sa.types.TypeEngine]] = [
    ("ssn", sa.String(11)),
    ("address1", sa.String(200)),
    ("address2", sa.String(200)),
    ("city", sa.String(100)),
    ("state", sa.String(20)),
    ("zip", sa.String(20)),
]


def upgrade() -> None:
    for table in _TABLES:
        # sasid was VARCHAR(10) (sized for SASID specifically); rilds_id is
        # generic and must hold any agency's id, so rename then widen.
        op.alter_column(table, "sasid", new_column_name="rilds_id", schema="rilds")
        op.alter_column(
            table, "rilds_id", type_=sa.String(50), schema="rilds"
        )
        for name, col_type in _NEW_COLUMNS:
            op.add_column(table, sa.Column(name, col_type, nullable=True), schema="rilds")

    # Only rilds_stage had an explicit hand-written index on this column
    # (idx_stage_sasid); member_universe's index is dropped/recreated by name
    # below too since it shares the same rename.
    op.drop_index("idx_stage_sasid", table_name="rilds_stage", schema="rilds")
    op.create_index(
        "idx_stage_rilds_id", "rilds_stage", ["rilds_id"], schema="rilds"
    )
    op.drop_index("idx_member_sasid", table_name="member_universe", schema="rilds")
    op.create_index(
        "idx_member_rilds_id", "member_universe", ["rilds_id"], schema="rilds"
    )


def downgrade() -> None:
    op.drop_index("idx_member_rilds_id", table_name="member_universe", schema="rilds")
    op.create_index(
        "idx_member_sasid", "member_universe", ["sasid"], schema="rilds"
    )
    op.drop_index("idx_stage_rilds_id", table_name="rilds_stage", schema="rilds")
    op.create_index(
        "idx_stage_sasid", "rilds_stage", ["sasid"], schema="rilds"
    )

    for table in _TABLES:
        for name, _col_type in reversed(_NEW_COLUMNS):
            op.drop_column(table, name, schema="rilds")
        op.alter_column(table, "rilds_id", type_=sa.String(10), schema="rilds")
        op.alter_column(table, "rilds_id", new_column_name="sasid", schema="rilds")
